/*
* generated by Xtext
*/
package org.macjariel.karel.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class KarelOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
