/*
* generated by Xtext
*/
package org.macjariel.karel.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.macjariel.karel.services.KarelGrammarAccess;

public class KarelParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private KarelGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.macjariel.karel.parser.antlr.internal.InternalKarelParser createParser(XtextTokenStream stream) {
		return new org.macjariel.karel.parser.antlr.internal.InternalKarelParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}
	
	public KarelGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(KarelGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
