/*
* generated by Xtext
*/

package org.macjariel.karel.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class KarelGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ProgramElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Program");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBEGINPROGRAMKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cInitSectionAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cInitSectionInitSectionParserRuleCall_1_0 = (RuleCall)cInitSectionAssignment_1.eContents().get(0);
		private final Assignment cUserDefinedCommandsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cUserDefinedCommandsUserDefinedCommandParserRuleCall_2_0 = (RuleCall)cUserDefinedCommandsAssignment_2.eContents().get(0);
		private final Assignment cMainAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cMainMainParserRuleCall_3_0 = (RuleCall)cMainAssignment_3.eContents().get(0);
		private final Keyword cENDPROGRAMKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Program:
		//	"BEGIN-PROGRAM" initSection=InitSection? userDefinedCommands+=UserDefinedCommand* main=Main "END-PROGRAM";
		public ParserRule getRule() { return rule; }

		//"BEGIN-PROGRAM" initSection=InitSection? userDefinedCommands+=UserDefinedCommand* main=Main "END-PROGRAM"
		public Group getGroup() { return cGroup; }

		//"BEGIN-PROGRAM"
		public Keyword getBEGINPROGRAMKeyword_0() { return cBEGINPROGRAMKeyword_0; }

		//initSection=InitSection?
		public Assignment getInitSectionAssignment_1() { return cInitSectionAssignment_1; }

		//InitSection
		public RuleCall getInitSectionInitSectionParserRuleCall_1_0() { return cInitSectionInitSectionParserRuleCall_1_0; }

		//userDefinedCommands+=UserDefinedCommand*
		public Assignment getUserDefinedCommandsAssignment_2() { return cUserDefinedCommandsAssignment_2; }

		//UserDefinedCommand
		public RuleCall getUserDefinedCommandsUserDefinedCommandParserRuleCall_2_0() { return cUserDefinedCommandsUserDefinedCommandParserRuleCall_2_0; }

		//main=Main
		public Assignment getMainAssignment_3() { return cMainAssignment_3; }

		//Main
		public RuleCall getMainMainParserRuleCall_3_0() { return cMainMainParserRuleCall_3_0; }

		//"END-PROGRAM"
		public Keyword getENDPROGRAMKeyword_4() { return cENDPROGRAMKeyword_4; }
	}

	public class InitSectionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "InitSection");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBEGININITKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cInitCommandsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cInitCommandsInitCommandParserRuleCall_1_0 = (RuleCall)cInitCommandsAssignment_1.eContents().get(0);
		private final Keyword cENDINITKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//InitSection:
		//	"BEGIN-INIT" initCommands+=InitCommand+ "END-INIT";
		public ParserRule getRule() { return rule; }

		//"BEGIN-INIT" initCommands+=InitCommand+ "END-INIT"
		public Group getGroup() { return cGroup; }

		//"BEGIN-INIT"
		public Keyword getBEGININITKeyword_0() { return cBEGININITKeyword_0; }

		//initCommands+=InitCommand+
		public Assignment getInitCommandsAssignment_1() { return cInitCommandsAssignment_1; }

		//InitCommand
		public RuleCall getInitCommandsInitCommandParserRuleCall_1_0() { return cInitCommandsInitCommandParserRuleCall_1_0; }

		//"END-INIT"
		public Keyword getENDINITKeyword_2() { return cENDINITKeyword_2; }
	}

	public class InitCommandElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "InitCommand");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cInitPositionCommandParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cInitHeadingCommandParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cInitBoardSizeCommandParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//InitCommand:
		//	InitPositionCommand | InitHeadingCommand | InitBoardSizeCommand;
		public ParserRule getRule() { return rule; }

		//InitPositionCommand | InitHeadingCommand | InitBoardSizeCommand
		public Alternatives getAlternatives() { return cAlternatives; }

		//InitPositionCommand
		public RuleCall getInitPositionCommandParserRuleCall_0() { return cInitPositionCommandParserRuleCall_0; }

		//InitHeadingCommand
		public RuleCall getInitHeadingCommandParserRuleCall_1() { return cInitHeadingCommandParserRuleCall_1; }

		//InitBoardSizeCommand
		public RuleCall getInitBoardSizeCommandParserRuleCall_2() { return cInitBoardSizeCommandParserRuleCall_2; }
	}

	public class InitPositionCommandElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "InitPositionCommand");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPositionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cXAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cXINTTerminalRuleCall_1_0 = (RuleCall)cXAssignment_1.eContents().get(0);
		private final Keyword cCommaKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cYAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cYINTTerminalRuleCall_3_0 = (RuleCall)cYAssignment_3.eContents().get(0);
		private final Keyword cSemicolonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//InitPositionCommand:
		//	"position" x=INT "," y=INT ";";
		public ParserRule getRule() { return rule; }

		//"position" x=INT "," y=INT ";"
		public Group getGroup() { return cGroup; }

		//"position"
		public Keyword getPositionKeyword_0() { return cPositionKeyword_0; }

		//x=INT
		public Assignment getXAssignment_1() { return cXAssignment_1; }

		//INT
		public RuleCall getXINTTerminalRuleCall_1_0() { return cXINTTerminalRuleCall_1_0; }

		//","
		public Keyword getCommaKeyword_2() { return cCommaKeyword_2; }

		//y=INT
		public Assignment getYAssignment_3() { return cYAssignment_3; }

		//INT
		public RuleCall getYINTTerminalRuleCall_3_0() { return cYINTTerminalRuleCall_3_0; }

		//";"
		public Keyword getSemicolonKeyword_4() { return cSemicolonKeyword_4; }
	}

	public class InitHeadingCommandElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "InitHeadingCommand");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHeadingKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cHeadingAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cHeadingHeadingKindParserRuleCall_1_0 = (RuleCall)cHeadingAssignment_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//InitHeadingCommand:
		//	"heading" heading=HeadingKind ";";
		public ParserRule getRule() { return rule; }

		//"heading" heading=HeadingKind ";"
		public Group getGroup() { return cGroup; }

		//"heading"
		public Keyword getHeadingKeyword_0() { return cHeadingKeyword_0; }

		//heading=HeadingKind
		public Assignment getHeadingAssignment_1() { return cHeadingAssignment_1; }

		//HeadingKind
		public RuleCall getHeadingHeadingKindParserRuleCall_1_0() { return cHeadingHeadingKindParserRuleCall_1_0; }

		//";"
		public Keyword getSemicolonKeyword_2() { return cSemicolonKeyword_2; }
	}

	public class InitBoardSizeCommandElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "InitBoardSizeCommand");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBoardSizeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cWidthAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cWidthINTTerminalRuleCall_1_0 = (RuleCall)cWidthAssignment_1.eContents().get(0);
		private final Keyword cCommaKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cHeightAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cHeightINTTerminalRuleCall_3_0 = (RuleCall)cHeightAssignment_3.eContents().get(0);
		private final Keyword cSemicolonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//InitBoardSizeCommand:
		//	"boardSize" width=INT "," height=INT ";";
		public ParserRule getRule() { return rule; }

		//"boardSize" width=INT "," height=INT ";"
		public Group getGroup() { return cGroup; }

		//"boardSize"
		public Keyword getBoardSizeKeyword_0() { return cBoardSizeKeyword_0; }

		//width=INT
		public Assignment getWidthAssignment_1() { return cWidthAssignment_1; }

		//INT
		public RuleCall getWidthINTTerminalRuleCall_1_0() { return cWidthINTTerminalRuleCall_1_0; }

		//","
		public Keyword getCommaKeyword_2() { return cCommaKeyword_2; }

		//height=INT
		public Assignment getHeightAssignment_3() { return cHeightAssignment_3; }

		//INT
		public RuleCall getHeightINTTerminalRuleCall_3_0() { return cHeightINTTerminalRuleCall_3_0; }

		//";"
		public Keyword getSemicolonKeyword_4() { return cSemicolonKeyword_4; }
	}

	public class HeadingKindElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "HeadingKind");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cNORTHKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cSOUTHKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cWESTKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cEASTKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		
		//HeadingKind:
		//	"NORTH" | "SOUTH" | "WEST" | "EAST";
		public ParserRule getRule() { return rule; }

		//"NORTH" | "SOUTH" | "WEST" | "EAST"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"NORTH"
		public Keyword getNORTHKeyword_0() { return cNORTHKeyword_0; }

		//"SOUTH"
		public Keyword getSOUTHKeyword_1() { return cSOUTHKeyword_1; }

		//"WEST"
		public Keyword getWESTKeyword_2() { return cWESTKeyword_2; }

		//"EAST"
		public Keyword getEASTKeyword_3() { return cEASTKeyword_3; }
	}

	public class UserDefinedCommandElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "UserDefinedCommand");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cDocAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cDocDocumentationCommentParserRuleCall_0_0 = (RuleCall)cDocAssignment_0.eContents().get(0);
		private final Keyword cDEFINECOMMANDKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cASKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cBEGINKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cStatementsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cStatementsStatementParserRuleCall_5_0 = (RuleCall)cStatementsAssignment_5.eContents().get(0);
		private final Keyword cENDKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//UserDefinedCommand:
		//	doc=DocumentationComment? "DEFINE COMMAND" name=ID "AS" "BEGIN" statements+=Statement* "END";
		public ParserRule getRule() { return rule; }

		//doc=DocumentationComment? "DEFINE COMMAND" name=ID "AS" "BEGIN" statements+=Statement* "END"
		public Group getGroup() { return cGroup; }

		//doc=DocumentationComment?
		public Assignment getDocAssignment_0() { return cDocAssignment_0; }

		//DocumentationComment
		public RuleCall getDocDocumentationCommentParserRuleCall_0_0() { return cDocDocumentationCommentParserRuleCall_0_0; }

		//"DEFINE COMMAND"
		public Keyword getDEFINECOMMANDKeyword_1() { return cDEFINECOMMANDKeyword_1; }

		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }

		//"AS"
		public Keyword getASKeyword_3() { return cASKeyword_3; }

		//"BEGIN"
		public Keyword getBEGINKeyword_4() { return cBEGINKeyword_4; }

		//statements+=Statement*
		public Assignment getStatementsAssignment_5() { return cStatementsAssignment_5; }

		//Statement
		public RuleCall getStatementsStatementParserRuleCall_5_0() { return cStatementsStatementParserRuleCall_5_0; }

		//"END"
		public Keyword getENDKeyword_6() { return cENDKeyword_6; }
	}

	public class MainElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Main");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMainAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cBEGINMAINKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cStatementsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cStatementsStatementParserRuleCall_2_0 = (RuleCall)cStatementsAssignment_2.eContents().get(0);
		private final Keyword cENDMAINKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Main:
		//	{Main} "BEGIN-MAIN" statements+=Statement* "END-MAIN";
		public ParserRule getRule() { return rule; }

		//{Main} "BEGIN-MAIN" statements+=Statement* "END-MAIN"
		public Group getGroup() { return cGroup; }

		//{Main}
		public Action getMainAction_0() { return cMainAction_0; }

		//"BEGIN-MAIN"
		public Keyword getBEGINMAINKeyword_1() { return cBEGINMAINKeyword_1; }

		//statements+=Statement*
		public Assignment getStatementsAssignment_2() { return cStatementsAssignment_2; }

		//Statement
		public RuleCall getStatementsStatementParserRuleCall_2_0() { return cStatementsStatementParserRuleCall_2_0; }

		//"END-MAIN"
		public Keyword getENDMAINKeyword_3() { return cENDMAINKeyword_3; }
	}

	public class StatementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Statement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cIfStatementParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIterateStatementParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cWhileStatementParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cCommandStatementParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cUserDefinedCommandStatementParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		
		//Statement:
		//	IfStatement | IterateStatement | WhileStatement | CommandStatement | UserDefinedCommandStatement;
		public ParserRule getRule() { return rule; }

		//IfStatement | IterateStatement | WhileStatement | CommandStatement | UserDefinedCommandStatement
		public Alternatives getAlternatives() { return cAlternatives; }

		//IfStatement
		public RuleCall getIfStatementParserRuleCall_0() { return cIfStatementParserRuleCall_0; }

		//IterateStatement
		public RuleCall getIterateStatementParserRuleCall_1() { return cIterateStatementParserRuleCall_1; }

		//WhileStatement
		public RuleCall getWhileStatementParserRuleCall_2() { return cWhileStatementParserRuleCall_2; }

		//CommandStatement
		public RuleCall getCommandStatementParserRuleCall_3() { return cCommandStatementParserRuleCall_3; }

		//UserDefinedCommandStatement
		public RuleCall getUserDefinedCommandStatementParserRuleCall_4() { return cUserDefinedCommandStatementParserRuleCall_4; }
	}

	public class UserDefinedCommandStatementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "UserDefinedCommandStatement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cCommandAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cCommandUserDefinedCommandCrossReference_0_0 = (CrossReference)cCommandAssignment_0.eContents().get(0);
		private final RuleCall cCommandUserDefinedCommandIDTerminalRuleCall_0_0_1 = (RuleCall)cCommandUserDefinedCommandCrossReference_0_0.eContents().get(1);
		private final Keyword cSemicolonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//UserDefinedCommandStatement:
		//	command=[UserDefinedCommand] ";";
		public ParserRule getRule() { return rule; }

		//command=[UserDefinedCommand] ";"
		public Group getGroup() { return cGroup; }

		//command=[UserDefinedCommand]
		public Assignment getCommandAssignment_0() { return cCommandAssignment_0; }

		//[UserDefinedCommand]
		public CrossReference getCommandUserDefinedCommandCrossReference_0_0() { return cCommandUserDefinedCommandCrossReference_0_0; }

		//ID
		public RuleCall getCommandUserDefinedCommandIDTerminalRuleCall_0_0_1() { return cCommandUserDefinedCommandIDTerminalRuleCall_0_0_1; }

		//";"
		public Keyword getSemicolonKeyword_1() { return cSemicolonKeyword_1; }
	}

	public class IfStatementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "IfStatement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cIFKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cConditionAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cConditionConditionExprParserRuleCall_2_0 = (RuleCall)cConditionAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cStatementsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cStatementsStatementParserRuleCall_5_0 = (RuleCall)cStatementsAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cELSEKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cElseStatementsAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cElseStatementsStatementParserRuleCall_7_2_0 = (RuleCall)cElseStatementsAssignment_7_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_3 = (Keyword)cGroup_7.eContents().get(3);
		
		//IfStatement:
		//	"IF" "(" condition=ConditionExpr ")" "{" statements+=Statement* "}" ("ELSE" "{" elseStatements+=Statement* "}")?;
		public ParserRule getRule() { return rule; }

		//"IF" "(" condition=ConditionExpr ")" "{" statements+=Statement* "}" ("ELSE" "{" elseStatements+=Statement* "}")?
		public Group getGroup() { return cGroup; }

		//"IF"
		public Keyword getIFKeyword_0() { return cIFKeyword_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }

		//condition=ConditionExpr
		public Assignment getConditionAssignment_2() { return cConditionAssignment_2; }

		//ConditionExpr
		public RuleCall getConditionConditionExprParserRuleCall_2_0() { return cConditionConditionExprParserRuleCall_2_0; }

		//")"
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }

		//statements+=Statement*
		public Assignment getStatementsAssignment_5() { return cStatementsAssignment_5; }

		//Statement
		public RuleCall getStatementsStatementParserRuleCall_5_0() { return cStatementsStatementParserRuleCall_5_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }

		//("ELSE" "{" elseStatements+=Statement* "}")?
		public Group getGroup_7() { return cGroup_7; }

		//"ELSE"
		public Keyword getELSEKeyword_7_0() { return cELSEKeyword_7_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }

		//elseStatements+=Statement*
		public Assignment getElseStatementsAssignment_7_2() { return cElseStatementsAssignment_7_2; }

		//Statement
		public RuleCall getElseStatementsStatementParserRuleCall_7_2_0() { return cElseStatementsStatementParserRuleCall_7_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7_3() { return cRightCurlyBracketKeyword_7_3; }
	}

	public class IterateStatementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "IterateStatement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cITERATEKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTimesAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTimesINTTerminalRuleCall_1_0 = (RuleCall)cTimesAssignment_1.eContents().get(0);
		private final Keyword cTIMESKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cStatementsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cStatementsStatementParserRuleCall_4_0 = (RuleCall)cStatementsAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//IterateStatement:
		//	"ITERATE" times=INT "TIMES" "{" statements+=Statement "}";
		public ParserRule getRule() { return rule; }

		//"ITERATE" times=INT "TIMES" "{" statements+=Statement "}"
		public Group getGroup() { return cGroup; }

		//"ITERATE"
		public Keyword getITERATEKeyword_0() { return cITERATEKeyword_0; }

		//times=INT
		public Assignment getTimesAssignment_1() { return cTimesAssignment_1; }

		//INT
		public RuleCall getTimesINTTerminalRuleCall_1_0() { return cTimesINTTerminalRuleCall_1_0; }

		//"TIMES"
		public Keyword getTIMESKeyword_2() { return cTIMESKeyword_2; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//statements+=Statement
		public Assignment getStatementsAssignment_4() { return cStatementsAssignment_4; }

		//Statement
		public RuleCall getStatementsStatementParserRuleCall_4_0() { return cStatementsStatementParserRuleCall_4_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class WhileStatementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "WhileStatement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cWHILEKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cConditionAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cConditionConditionExprParserRuleCall_2_0 = (RuleCall)cConditionAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cStatementsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cStatementsStatementParserRuleCall_5_0 = (RuleCall)cStatementsAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//WhileStatement:
		//	"WHILE" "(" condition=ConditionExpr ")" "{" statements+=Statement "}";
		public ParserRule getRule() { return rule; }

		//"WHILE" "(" condition=ConditionExpr ")" "{" statements+=Statement "}"
		public Group getGroup() { return cGroup; }

		//"WHILE"
		public Keyword getWHILEKeyword_0() { return cWHILEKeyword_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }

		//condition=ConditionExpr
		public Assignment getConditionAssignment_2() { return cConditionAssignment_2; }

		//ConditionExpr
		public RuleCall getConditionConditionExprParserRuleCall_2_0() { return cConditionConditionExprParserRuleCall_2_0; }

		//")"
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }

		//statements+=Statement
		public Assignment getStatementsAssignment_5() { return cStatementsAssignment_5; }

		//Statement
		public RuleCall getStatementsStatementParserRuleCall_5_0() { return cStatementsStatementParserRuleCall_5_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class DocumentationCommentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "DocumentationComment");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCommercialAtLeftParenthesisKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTextAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTextSTRINGTerminalRuleCall_1_0 = (RuleCall)cTextAssignment_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//DocumentationComment:
		//	"@(" text=STRING ")";
		public ParserRule getRule() { return rule; }

		//"@(" text=STRING ")"
		public Group getGroup() { return cGroup; }

		//"@("
		public Keyword getCommercialAtLeftParenthesisKeyword_0() { return cCommercialAtLeftParenthesisKeyword_0; }

		//text=STRING
		public Assignment getTextAssignment_1() { return cTextAssignment_1; }

		//STRING
		public RuleCall getTextSTRINGTerminalRuleCall_1_0() { return cTextSTRINGTerminalRuleCall_1_0; }

		//")"
		public Keyword getRightParenthesisKeyword_2() { return cRightParenthesisKeyword_2; }
	}

	public class CommandStatementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "CommandStatement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cKindAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cKindCommandKindParserRuleCall_0_0 = (RuleCall)cKindAssignment_0.eContents().get(0);
		private final Keyword cSemicolonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//CommandStatement:
		//	kind=CommandKind ";";
		public ParserRule getRule() { return rule; }

		//kind=CommandKind ";"
		public Group getGroup() { return cGroup; }

		//kind=CommandKind
		public Assignment getKindAssignment_0() { return cKindAssignment_0; }

		//CommandKind
		public RuleCall getKindCommandKindParserRuleCall_0_0() { return cKindCommandKindParserRuleCall_0_0; }

		//";"
		public Keyword getSemicolonKeyword_1() { return cSemicolonKeyword_1; }
	}

	public class CommandKindElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "CommandKind");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cMoveKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cTurnKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cTurnOnKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cTurnOffKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		private final Keyword cPutKeyword_4 = (Keyword)cAlternatives.eContents().get(4);
		private final Keyword cGetKeyword_5 = (Keyword)cAlternatives.eContents().get(5);
		
		//CommandKind:
		//	"move" | "turn" | "turnOn" | "turnOff" | "put" | "get";
		public ParserRule getRule() { return rule; }

		//"move" | "turn" | "turnOn" | "turnOff" | "put" | "get"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"move"
		public Keyword getMoveKeyword_0() { return cMoveKeyword_0; }

		//"turn"
		public Keyword getTurnKeyword_1() { return cTurnKeyword_1; }

		//"turnOn"
		public Keyword getTurnOnKeyword_2() { return cTurnOnKeyword_2; }

		//"turnOff"
		public Keyword getTurnOffKeyword_3() { return cTurnOffKeyword_3; }

		//"put"
		public Keyword getPutKeyword_4() { return cPutKeyword_4; }

		//"get"
		public Keyword getGetKeyword_5() { return cGetKeyword_5; }
	}

	public class ConditionExprElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ConditionExpr");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNegationAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cNegationExclamationMarkKeyword_0_0 = (Keyword)cNegationAssignment_0.eContents().get(0);
		private final Assignment cExprAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cExprConditionKindParserRuleCall_1_0 = (RuleCall)cExprAssignment_1.eContents().get(0);
		
		//ConditionExpr:
		//	negation?="!" expr=ConditionKind;
		public ParserRule getRule() { return rule; }

		//negation?="!" expr=ConditionKind
		public Group getGroup() { return cGroup; }

		//negation?="!"
		public Assignment getNegationAssignment_0() { return cNegationAssignment_0; }

		//"!"
		public Keyword getNegationExclamationMarkKeyword_0_0() { return cNegationExclamationMarkKeyword_0_0; }

		//expr=ConditionKind
		public Assignment getExprAssignment_1() { return cExprAssignment_1; }

		//ConditionKind
		public RuleCall getExprConditionKindParserRuleCall_1_0() { return cExprConditionKindParserRuleCall_1_0; }
	}

	public class ConditionKindElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ConditionKind");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cWALL_AHEADKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cMARKED_PLACEKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//ConditionKind:
		//	"WALL_AHEAD" | "MARKED_PLACE";
		public ParserRule getRule() { return rule; }

		//"WALL_AHEAD" | "MARKED_PLACE"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"WALL_AHEAD"
		public Keyword getWALL_AHEADKeyword_0() { return cWALL_AHEADKeyword_0; }

		//"MARKED_PLACE"
		public Keyword getMARKED_PLACEKeyword_1() { return cMARKED_PLACEKeyword_1; }
	}
	
	
	private ProgramElements pProgram;
	private InitSectionElements pInitSection;
	private InitCommandElements pInitCommand;
	private InitPositionCommandElements pInitPositionCommand;
	private InitHeadingCommandElements pInitHeadingCommand;
	private InitBoardSizeCommandElements pInitBoardSizeCommand;
	private HeadingKindElements pHeadingKind;
	private UserDefinedCommandElements pUserDefinedCommand;
	private MainElements pMain;
	private StatementElements pStatement;
	private UserDefinedCommandStatementElements pUserDefinedCommandStatement;
	private IfStatementElements pIfStatement;
	private IterateStatementElements pIterateStatement;
	private WhileStatementElements pWhileStatement;
	private DocumentationCommentElements pDocumentationComment;
	private CommandStatementElements pCommandStatement;
	private CommandKindElements pCommandKind;
	private ConditionExprElements pConditionExpr;
	private ConditionKindElements pConditionKind;
	
	private final GrammarProvider grammarProvider;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public KarelGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammarProvider = grammarProvider;
		this.gaTerminals = gaTerminals;
	}
	
	public Grammar getGrammar() {	
		return grammarProvider.getGrammar(this);
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Program:
	//	"BEGIN-PROGRAM" initSection=InitSection? userDefinedCommands+=UserDefinedCommand* main=Main "END-PROGRAM";
	public ProgramElements getProgramAccess() {
		return (pProgram != null) ? pProgram : (pProgram = new ProgramElements());
	}
	
	public ParserRule getProgramRule() {
		return getProgramAccess().getRule();
	}

	//InitSection:
	//	"BEGIN-INIT" initCommands+=InitCommand+ "END-INIT";
	public InitSectionElements getInitSectionAccess() {
		return (pInitSection != null) ? pInitSection : (pInitSection = new InitSectionElements());
	}
	
	public ParserRule getInitSectionRule() {
		return getInitSectionAccess().getRule();
	}

	//InitCommand:
	//	InitPositionCommand | InitHeadingCommand | InitBoardSizeCommand;
	public InitCommandElements getInitCommandAccess() {
		return (pInitCommand != null) ? pInitCommand : (pInitCommand = new InitCommandElements());
	}
	
	public ParserRule getInitCommandRule() {
		return getInitCommandAccess().getRule();
	}

	//InitPositionCommand:
	//	"position" x=INT "," y=INT ";";
	public InitPositionCommandElements getInitPositionCommandAccess() {
		return (pInitPositionCommand != null) ? pInitPositionCommand : (pInitPositionCommand = new InitPositionCommandElements());
	}
	
	public ParserRule getInitPositionCommandRule() {
		return getInitPositionCommandAccess().getRule();
	}

	//InitHeadingCommand:
	//	"heading" heading=HeadingKind ";";
	public InitHeadingCommandElements getInitHeadingCommandAccess() {
		return (pInitHeadingCommand != null) ? pInitHeadingCommand : (pInitHeadingCommand = new InitHeadingCommandElements());
	}
	
	public ParserRule getInitHeadingCommandRule() {
		return getInitHeadingCommandAccess().getRule();
	}

	//InitBoardSizeCommand:
	//	"boardSize" width=INT "," height=INT ";";
	public InitBoardSizeCommandElements getInitBoardSizeCommandAccess() {
		return (pInitBoardSizeCommand != null) ? pInitBoardSizeCommand : (pInitBoardSizeCommand = new InitBoardSizeCommandElements());
	}
	
	public ParserRule getInitBoardSizeCommandRule() {
		return getInitBoardSizeCommandAccess().getRule();
	}

	//HeadingKind:
	//	"NORTH" | "SOUTH" | "WEST" | "EAST";
	public HeadingKindElements getHeadingKindAccess() {
		return (pHeadingKind != null) ? pHeadingKind : (pHeadingKind = new HeadingKindElements());
	}
	
	public ParserRule getHeadingKindRule() {
		return getHeadingKindAccess().getRule();
	}

	//UserDefinedCommand:
	//	doc=DocumentationComment? "DEFINE COMMAND" name=ID "AS" "BEGIN" statements+=Statement* "END";
	public UserDefinedCommandElements getUserDefinedCommandAccess() {
		return (pUserDefinedCommand != null) ? pUserDefinedCommand : (pUserDefinedCommand = new UserDefinedCommandElements());
	}
	
	public ParserRule getUserDefinedCommandRule() {
		return getUserDefinedCommandAccess().getRule();
	}

	//Main:
	//	{Main} "BEGIN-MAIN" statements+=Statement* "END-MAIN";
	public MainElements getMainAccess() {
		return (pMain != null) ? pMain : (pMain = new MainElements());
	}
	
	public ParserRule getMainRule() {
		return getMainAccess().getRule();
	}

	//Statement:
	//	IfStatement | IterateStatement | WhileStatement | CommandStatement | UserDefinedCommandStatement;
	public StatementElements getStatementAccess() {
		return (pStatement != null) ? pStatement : (pStatement = new StatementElements());
	}
	
	public ParserRule getStatementRule() {
		return getStatementAccess().getRule();
	}

	//UserDefinedCommandStatement:
	//	command=[UserDefinedCommand] ";";
	public UserDefinedCommandStatementElements getUserDefinedCommandStatementAccess() {
		return (pUserDefinedCommandStatement != null) ? pUserDefinedCommandStatement : (pUserDefinedCommandStatement = new UserDefinedCommandStatementElements());
	}
	
	public ParserRule getUserDefinedCommandStatementRule() {
		return getUserDefinedCommandStatementAccess().getRule();
	}

	//IfStatement:
	//	"IF" "(" condition=ConditionExpr ")" "{" statements+=Statement* "}" ("ELSE" "{" elseStatements+=Statement* "}")?;
	public IfStatementElements getIfStatementAccess() {
		return (pIfStatement != null) ? pIfStatement : (pIfStatement = new IfStatementElements());
	}
	
	public ParserRule getIfStatementRule() {
		return getIfStatementAccess().getRule();
	}

	//IterateStatement:
	//	"ITERATE" times=INT "TIMES" "{" statements+=Statement "}";
	public IterateStatementElements getIterateStatementAccess() {
		return (pIterateStatement != null) ? pIterateStatement : (pIterateStatement = new IterateStatementElements());
	}
	
	public ParserRule getIterateStatementRule() {
		return getIterateStatementAccess().getRule();
	}

	//WhileStatement:
	//	"WHILE" "(" condition=ConditionExpr ")" "{" statements+=Statement "}";
	public WhileStatementElements getWhileStatementAccess() {
		return (pWhileStatement != null) ? pWhileStatement : (pWhileStatement = new WhileStatementElements());
	}
	
	public ParserRule getWhileStatementRule() {
		return getWhileStatementAccess().getRule();
	}

	//DocumentationComment:
	//	"@(" text=STRING ")";
	public DocumentationCommentElements getDocumentationCommentAccess() {
		return (pDocumentationComment != null) ? pDocumentationComment : (pDocumentationComment = new DocumentationCommentElements());
	}
	
	public ParserRule getDocumentationCommentRule() {
		return getDocumentationCommentAccess().getRule();
	}

	//CommandStatement:
	//	kind=CommandKind ";";
	public CommandStatementElements getCommandStatementAccess() {
		return (pCommandStatement != null) ? pCommandStatement : (pCommandStatement = new CommandStatementElements());
	}
	
	public ParserRule getCommandStatementRule() {
		return getCommandStatementAccess().getRule();
	}

	//CommandKind:
	//	"move" | "turn" | "turnOn" | "turnOff" | "put" | "get";
	public CommandKindElements getCommandKindAccess() {
		return (pCommandKind != null) ? pCommandKind : (pCommandKind = new CommandKindElements());
	}
	
	public ParserRule getCommandKindRule() {
		return getCommandKindAccess().getRule();
	}

	//ConditionExpr:
	//	negation?="!" expr=ConditionKind;
	public ConditionExprElements getConditionExprAccess() {
		return (pConditionExpr != null) ? pConditionExpr : (pConditionExpr = new ConditionExprElements());
	}
	
	public ParserRule getConditionExprRule() {
		return getConditionExprAccess().getRule();
	}

	//ConditionKind:
	//	"WALL_AHEAD" | "MARKED_PLACE";
	public ConditionKindElements getConditionKindAccess() {
		return (pConditionKind != null) ? pConditionKind : (pConditionKind = new ConditionKindElements());
	}
	
	public ParserRule getConditionKindRule() {
		return getConditionKindAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
